version: '3.3'

services:
  svfe-api-firmador:
    image: svfe/svfe-api-firmador:v20230109
    container_name: svfe-api-firmador
    restart: unless-stopped
    ports:
      - "${PORT}:8113"
    environment:
      - NODE_ENV=production
    env_file:
      - .env  # Archivo separado para variables de entorno
    volumes:
      - "./certificados:/uploads"
    networks:
      - svfe_network

networks:
  svfe_network:
    driver: bridge

