version: '3.8'

services:
  svfe-api-firmador:
    image: svfe/svfe-api-firmador:v20230109
    container_name: svfe-api-firmador
    restart: unless-stopped
    ports:
      - "${PORT}:8113"
    environment:
      - NODE_ENV=production
    env_file:
      - .env  # Archivo separado para variables de entorno
    volumes:
      - svfe_temp:/uploads
    networks:
      - svfe_network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "120M"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  svfe_temp:

networks:
  svfe_network:
    driver: bridge

